name = "TrajectoryIndexingUtils"
uuid = "6dad8b7f-dd9a-4c28-9b70-85b9a079bfc8"
authors = ["Aaron Trowbridge <aaron.j.trowbridge@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.10, 1.11, 1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
